//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FontInfo
    {
        public int FontId { get; set; }
        public int FolderId { get; set; }
        public string FileName { get; set; }
        public System.DateTime FileDate { get; set; }
        public int FileSize { get; set; }
        public string FaceName { get; set; }
        public string FamilyName { get; set; }
        public string FontType { get; set; }
        public Nullable<decimal> Baseline { get; set; }
        public Nullable<decimal> CapsHeight { get; set; }
        public string Description { get; set; }
        public string ManufacturerName { get; set; }
        public Nullable<int> GlyphCount { get; set; }
        public Nullable<decimal> Height { get; set; }
        public string Stretch { get; set; }
        public string Style { get; set; }
        public Nullable<bool> Symbol { get; set; }
        public string Trademark { get; set; }
        public string Version { get; set; }
        public string Weight { get; set; }
        public Nullable<decimal> XHeight { get; set; }
        public string ErrorMessage { get; set; }
    
        public virtual Folder Folder { get; set; }
    }
}
