//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FontInfosEntities : DbContext
    {
        public FontInfosEntities()
            : base("name=FontInfosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Duplicate> Duplicates { get; set; }
        public virtual DbSet<Folder> Folders { get; set; }
        public virtual DbSet<FontInfo> Fonts { get; set; }
    }
}
